version: '3.8'

services:
  flask-app:
    build: .
    container_name: wethaq-flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MILVUS_URI=milvus://milvus:19530
      - COLLECTION_NAME=saudi_landmarks
    depends_on:
      - milvus

  milvus:
    image: milvusdb/milvus:2.0.0
    container_name: milvus
    ports:
      - "19530:19530"
    environment:
      - MILVUS_SINGLE_NODE=true
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  milvus_data:
